main_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('accounts/signup/', views.signup, name='signup'),
    path('', views.home, name='home'),
    path('workouts/', views.WorkoutList.as_view(), name='index'),
    path('workouts/<int:workout_id>/', views.workout_detail, name='detail'),
    path('workouts/create', views.WorkoutCreate.as_view(), name='workout_create'),
    path('workouts/<int:pk>/update', views.WorkoutUpdate.as_view(), name='workout_update'),
    path('workouts/<int:pk>/delete', views.WorkoutDelete.as_view(), name='workout_delete'),
    path('workouts/<int:workout_id>/add_exercise/', views.add_exercise, name='add_exercise'),
    path('workouts/<int:workout_id>/delete_exercise/<int:exercise_id>', views.delete_exercise, name='delete_exercise'),
    path('exercises/', views.ExerciseTypeList.as_view(), name='exercise_index'),
    path('exercises/<int:exercise_type_id>/', views.exercise_type_detail, name='exercise_detail'),
    path('exercises/create/', views.ExerciseTypeCreate.as_view(), name='exercise_create'),
    path('exercises/<int:pk>/update/', views.ExerciseTypeUpdate.as_view(), name='exercise_update'),
    path('exercises/<int:pk>/delete/', views.ExerciseTypeDelete.as_view(), name='exercise_delete'),
]

sweatlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.

class MuscleGroup(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class ExerciseType(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    muscle_groups = models.ManyToManyField(MuscleGroup)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("exercise_detail", kwargs={"exercise_type_id": self.id})


class Workout(models.Model):
    name = models.CharField(max_length=250)
    date = models.DateField('Workout Date')
    notes = models.TextField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} on {self.date}'
    
    def get_absolute_url(self):
        return reverse("detail", kwargs={"workout_id": self.id})
    
    class Meta:
        ordering = ['-date']
    
class Exercise(models.Model):
    exercise_type = models.ForeignKey(ExerciseType, on_delete=models.CASCADE)
    sets = models.IntegerField()
    reps = models.IntegerField()
    weight = models.DecimalField(max_digits=6, decimal_places=2)
    workout = models.ForeignKey(Workout, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.exercise_type.name} {self.sets} x {self.reps}'

main_app/forms.py
from django.forms import ModelForm
from .models import Exercise

class ExerciseForm(ModelForm):
    class Meta:
        model = Exercise
        fields = ['exercise_type', 'sets', 'reps', 'weight']

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Workout, Exercise, ExerciseType
from .forms import ExerciseForm
# Create your views here.

def home(request):
  return render(request, 'home.html')

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

@login_required
def workout_detail(request, workout_id):
  workout = Workout.objects.get(id=workout_id)
  exercise_form = ExerciseForm()
  return render(request, 'workouts/detail.html', {
    'workout': workout,
    'exercise_form': exercise_form
  })

def exercise_type_detail(request, exercise_type_id):
  exercise_type = ExerciseType.objects.get(id=exercise_type_id)
  print(exercise_type)
  return render(request, 'main_app/exercisetype_detail.html', {
    'exercise_type': exercise_type
  })

@login_required
def add_exercise(request, workout_id):
  form = ExerciseForm(request.POST)
  if form.is_valid():
    new_exercise = form.save(commit=False)
    new_exercise.workout_id = workout_id
    new_exercise.save()

  return redirect('detail', workout_id=workout_id)

@login_required
def delete_exercise(request, workout_id, exercise_id):
    exercise = Exercise.objects.get(id=exercise_id)
    print(exercise)
    exercise.delete()

    return redirect('detail', workout_id=workout_id)

class WorkoutList(LoginRequiredMixin, ListView):
  model = Workout

  def get_queryset(self):
    return Workout.objects.filter(user=self.request.user)
  
class WorkoutCreate(LoginRequiredMixin, CreateView):
  model = Workout
  fields = ['name', 'date', 'notes']

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)
  
class WorkoutUpdate(LoginRequiredMixin, UpdateView):
  model = Workout
  fields = ['name', 'date', 'notes']

class WorkoutDelete(LoginRequiredMixin, DeleteView):
  model = Workout
  success_url ='/workouts'

class ExerciseTypeList(ListView):
  model = ExerciseType

class ExerciseTypeCreate(LoginRequiredMixin, CreateView):
  model = ExerciseType
  fields = '__all__'

class ExerciseTypeUpdate(LoginRequiredMixin, UpdateView):
  model = ExerciseType
  fields = '__all__'

class ExerciseTypeDelete(LoginRequiredMixin, DeleteView):
  model = ExerciseType
  success_url = '/exercises'

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sweat Log</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="blue nav-wrapper">
                <ul>
                    <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Sweat Log</a></li>
                </ul>
                <ul class="right">
                  {% if user.is_authenticated %}
                    <li><a href="{% url "exercise_index" %}">View Exercises</a></li>
                    <li><a href="{% url "exercise_create" %}">Add Exercise Types</a></li>
                    <li><a href="{% url "workout_create" %}">Add Workout</a></li>
                    <li><a href="{% url "index" %}">View Workouts</a></li>
                    <li>
                        <form action="{% url 'logout' %}" method="POST">
                            {% csrf_token %}
                            <button id="logout-button">Log Out</button>
                        </form>
                    </li>
                  {% else %}
                  {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
  	<footer class="blue page-footer">
       <div class="right">All Rights Reserved, &copy; 2022 SweatLog &nbsp;</div>
    </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1 id="home">Welcome to Sweat Log</h1>

{% if user.is_authenticated %}
{% else %}
<div class="container">
    <div class="row">
        <div class="col s12 m6 offset-m3">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Login</span>
                    <form action="{% url "login" %}" method="POST">
                        {% csrf_token %}
                        <p>
                            <label for="id_username" class="active">Username:</label>
                            <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">
                        </p>
                        <p>
                            <label for="id_password" class="active">Password:</label>
                            <input type="password" name="password" autocomplete="current-password" required="" id="id_password">
                        </p>
                        <button type="submit" class="btn waves-effect waves-light blue">Login</button>
                        <a href="{% url 'signup' %}" class="btn waves-effect waves-light blue">Sign Up</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

main_app/templates/main_app/exercisetype_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Toy</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'exercise_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/exercisetype_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Exercise Details</h1>

<div class="row">
  <div class="col s12 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ exercise_type.name }}</span>
        <p>Muscles Worked: </p>
        {% for muscle in exercise_type.muscle_groups.all %}
            {{ muscle.name }}{% if not forloop.last %}, {% endif %}
        {% endfor %}
      </div>
      <div class="card-action">
        <a href="{% url 'exercise_update' exercise_type.id %}" class="blue-text">Edit</a>
        <a href="{% url 'exercise_delete' exercise_type.id %}" class="blue-text">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/exercisetype_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Exercise</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn blue">
  </form>

<script>
    const selectEl = document.getElementById('id_muscle_groups');
    M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/main_app/exercisetype_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Exercise Type List</h1>

{% for exercisetype in exercisetype_list %}
  <a href="{% url 'exercise_detail' exercisetype.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ exercisetype.name }}</span>
            <p>Description: {{ exercisetype.description }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/workout_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Workout</h1>

  <h4>Are you sure you want to delete <span class="blue-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn red">
    <a href="{% url 'detail' workout.id %}" class="btn waves-effect waves-light blue">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/workout_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
  <h1>Edit <span class="blue-text">{{ object.name }}</span></h1>
{% else %}
  <h1>Add Workout</h1>
{% endif %}


<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="POST">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn blue">
</form>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true,
    });
  });
</script>

{% endblock %}

main_app/templates/main_app/workout_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Workout List</h1>

{% for workout in workout_list %}
  <a href="{% url 'detail' workout.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ workout.name }}</span>
            <p>{{ workout.date }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/workouts/detail.html
{% extends "base.html" %}
{% block content %}

<h1>Workout Details</h1>

<div class="row">
    <div class="col s12">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ workout.name }}</span>
                <p>Date: {{ workout.date }}</p>
                <p class="notes">Notes: {{ workout.notes }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'workout_update' workout.id %}" class="blue-text">Edit</a>
                <a href="{% url 'workout_delete' workout.id %}" class="blue-text">Delete</a>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col s12">
        <form action="{% url "add_exercise" workout.id %}" method="POST">
            {% csrf_token %}
            {{ exercise_form.as_p }}
            <input type="submit" class="btn blue" value="Add Execercise">
        </form>
        <br>
        <table class="striped">
            <thead>
                <tr>
                    <th>Exercise</th>
                    <th>Sets</th>
                    <th>Reps</th>
                    <th>Weight</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for exercise in workout.exercise_set.all %}
                <tr>
                    <td>{{exercise.exercise_type.name}}</td>
                    <td>{{exercise.sets}}</td>
                    <td>{{exercise.reps}}</td>
                    <td>{{exercise.weight}}</td>
                    <td>
                        <form action="{% url "delete_exercise" workout.id exercise.id %}" method="POST">
                            {% csrf_token %}
                            <button class="btn waves-effect waves-light red">DELETE</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script>
    const selectEl = document.getElementById('id_exercise_type');
    M.FormSelect.init(selectEl);
</script>

{% endblock  %}